"""initial application schema

Revision ID: 0039fdbaddf3
Revises: 
Create Date: 2026-10-04 15:20:22.011557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0039fdbaddf3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dramas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('catalog_index', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('alternate_names', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.String(length=128), nullable=False),
    sa.Column('poster_key', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('rating_value', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('aired', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('watchers', sa.BigInteger(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_index'),
    sa.UniqueConstraint('image_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_dramas_title'), 'dramas', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('catalog_version', sa.String(length=100), nullable=False),
    sa.Column('result_drama_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_created_at'), 'recommendation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_events_session_id'), 'recommendation_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_user_id'), 'recommendation_events', ['user_id'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_created_at'), 'search_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_events_session_id'), 'search_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('preference_key', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_user_preferences_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'preference_key', name='uq_user_preference')
    )
    op.create_table('drama_credits',
    sa.Column('drama_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('billing_order', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("role IN ('actor', 'director', 'screenwriter')", name='ck_drama_credits_role'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drama_id', 'person_id', 'role')
    )
    op.create_table('drama_genres',
    sa.Column('drama_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drama_id', 'genre_id')
    )
    op.create_table('drama_keywords',
    sa.Column('drama_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drama_id', 'keyword_id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('drama_id', sa.BigInteger(), nullable=True),
    sa.Column('search_event_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_action'), 'interactions', ['action'], unique=False)
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactions_drama_id'), 'interactions', ['drama_id'], unique=False)
    op.create_index(op.f('ix_interactions_session_id'), 'interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drama_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_ratings_range'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'drama_id')
    )
    op.create_table('watchlist_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drama_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'watching', 'completed', 'paused', 'dropped')", name='ck_watchlist_items_status'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'drama_id')
    )
    op.create_foreign_key(
        'fk_profiles_user', 'profiles', 'users', ['id'], ['id'],
        source_schema='public', referent_schema='auth', ondelete='CASCADE'
    )
    for table_name in ('watchlist_items', 'ratings', 'user_preferences'):
        op.create_foreign_key(
            f'fk_{table_name}_user', table_name, 'users', ['user_id'], ['id'],
            source_schema='public', referent_schema='auth', ondelete='CASCADE'
        )
    for table_name in ('search_events', 'recommendation_events', 'interactions'):
        op.create_foreign_key(
            f'fk_{table_name}_user', table_name, 'users', ['user_id'], ['id'],
            source_schema='public', referent_schema='auth', ondelete='SET NULL'
        )

    op.execute("""
        CREATE FUNCTION public.set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = ''
        AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
    """)
    for table_name in (
        'dramas', 'profiles', 'watchlist_items', 'ratings', 'user_preferences'
    ):
        op.execute(f"""
            CREATE TRIGGER set_{table_name}_updated_at
            BEFORE UPDATE ON public.{table_name}
            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()
        """)

    catalog_tables = (
        'dramas', 'genres', 'drama_genres', 'people', 'drama_credits',
        'keywords', 'drama_keywords'
    )
    for table_name in catalog_tables:
        op.execute(f'ALTER TABLE public.{table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'REVOKE ALL ON TABLE public.{table_name} FROM anon, authenticated')
        op.execute(f'GRANT SELECT ON TABLE public.{table_name} TO anon, authenticated')
        op.execute(f"""
            CREATE POLICY {table_name}_public_read
            ON public.{table_name}
            FOR SELECT
            TO anon, authenticated
            USING (true)
        """)

    owned_tables = (
        'watchlist_items', 'ratings', 'user_preferences', 'search_events',
        'recommendation_events', 'interactions'
    )
    op.execute('ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY')
    op.execute('REVOKE ALL ON TABLE public.profiles FROM anon, authenticated')
    op.execute(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.profiles TO authenticated'
    )
    op.execute("""
        CREATE POLICY profiles_own_rows
        ON public.profiles
        FOR ALL
        TO authenticated
        USING ((SELECT auth.uid()) = id)
        WITH CHECK ((SELECT auth.uid()) = id)
    """)
    for table_name in owned_tables:
        op.execute(f'ALTER TABLE public.{table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'REVOKE ALL ON TABLE public.{table_name} FROM anon, authenticated')
        op.execute(
            f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.{table_name} '
            'TO authenticated'
        )
        op.execute(f"""
            CREATE POLICY {table_name}_own_rows
            ON public.{table_name}
            FOR ALL
            TO authenticated
            USING ((SELECT auth.uid()) = user_id)
            WITH CHECK ((SELECT auth.uid()) = user_id)
        """)
    op.execute(
        'GRANT USAGE, SELECT ON SEQUENCE public.user_preferences_id_seq '
        'TO authenticated'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_session_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_drama_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_action'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('drama_keywords')
    op.drop_table('drama_genres')
    op.drop_table('drama_credits')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_session_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_created_at'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_recommendation_events_user_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_session_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_created_at'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_table('profiles')
    op.drop_table('people')
    op.drop_table('keywords')
    op.drop_table('genres')
    op.drop_index(op.f('ix_dramas_title'), table_name='dramas')
    op.drop_table('dramas')
    op.execute('DROP FUNCTION IF EXISTS public.set_updated_at()')
    # ### end Alembic commands ###
